version: '3'

services:
  # Configuções para o MySQL
  db-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      
    volumes:
      - "~/data_db:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - app_network

  # Client Web para acessar o MYSQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - app_network
      
  # Configurações para o Redis
  redis_service:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app_network

  # Configurações para a aplicação.
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - db-mysql
      - redis_service
    ports:
      - 8000:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge