version: '3'

services:
  # Configuções para o MySQL
  db-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      #- MYSQL_USER=app_user
      #- MYSQL_PASSWORD=app_pass
      
    volumes:
      - "~/data:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - app_network

  # Client Web para acessar o MYSQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - app_network
      
  # Configurações para o Redis
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app_network

  # Configurações para a aplicação.
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - db-mysql
      - redis
    ports:
      - 8000:8000
    networks:
      - app_network
    #environment:
    #  SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/app_db?useSSL=false&allowPublicKeyRetrieval=true
    #environment:
    #  - DATABASE_HOST=db-mysql
    #  - DATABASE_USER=app_user
    #  - DATABASE_PASSWORD=app_pass
    #  - DATABASE_NAME=app_db
    #  - DATABASE_PORT=3306

networks:
  app_network:
    driver: bridge